### ISSUE TITLE
Tint app icons

### ISSUE THREAD

**Issue by JSEHV** [attah/harbour-tint#1]
I created some icons for your app. The shared links contain the svg and the png files.
Are these icons to your liking for your tint app? I hope so, so we can enjoy your app in the Jolla harbour store soon :)

Tint icons: https://ufile.io/p49kl

![harbour-tint-icon](https://user-images.githubusercontent.com/5128988/50047649-210e1980-00ba-11e9-8235-0263df369c00.png)
![harbour-tint-icon2](https://user-images.githubusercontent.com/5128988/50047650-210e1980-00ba-11e9-8a0a-ca7b03310748.png)
![harbour-tint-icon3](https://user-images.githubusercontent.com/5128988/50047651-210e1980-00ba-11e9-92c3-be655675f804.png)

Hue icons: https://ufile.io/jrzij

![hue-black-gradient](https://user-images.githubusercontent.com/5128988/50047653-2c614500-00ba-11e9-99b4-301fbf41d689.png)
![hue-gray-gradient](https://user-images.githubusercontent.com/5128988/50047654-2c614500-00ba-11e9-9fd7-4c1e02dd0274.png)
![hue-white](https://user-images.githubusercontent.com/5128988/50047655-2c614500-00ba-11e9-8157-2fbf3c18cc88.png)

**Comment by attah** [comment]
Nice! I'm quite partial to the shape of those black "Hue" icons (the darker is slightly better). I wouldn't want to get in to the legal quagmire of using "hue" in the name or logo though, so either that shape with one of those quite nice-looking luminaire designs or the word "tint" would be my ideal choice.

**Comment by JS1982** [comment]
Here you go :)

https://ufile.io/5b0hd

![harbour-tint-attah1](https://user-images.githubusercontent.com/5128988/50047809-96c7b480-00bd-11e9-9bec-c8bd81b53045.png)
![harbour-tint-attah2](https://user-images.githubusercontent.com/5128988/50047810-97604b00-00bd-11e9-863e-dac1645c4214.png)
![harbour-tint-attah3](https://user-images.githubusercontent.com/5128988/50047811-97604b00-00bd-11e9-88cb-ce090c33d74a.png)

**Comment by attah** [comment]
I agree completely, that one looks perfect. However, there seems to be something wrong with the upload with all sizes i get a 0k zip archive...

**Comment by JSEHV** [comment]
Forgot that you can drag zip files also to GitHub (noob error ;)) 

[harbour-tint-attah-all-sizes.zip](https://github.com/attah/harbour-tint/files/2683533/harbour-tint-attah-all-sizes.zip)
