### ISSUE TITLE
Local discovery

### ISSUE THREAD

**Issue by attah** [attah/harbour-tint#12]
Implement local discovery (see http://www.burgestrand.se/hue-api/api/discovery/) to make it not rely on having Internet connectivity. This likely requires a partial rewrite to introduce C++ components. :(

**Comment by paulvt** [comment]
I usually block the internet connection for my bridge, so I would appreciate this feature.

However, I noticed that if you temporarily enable the internet connection, pair with the bridge, disable it again it is not in the list? Would it be possible to have the list separated into:

* Paired bridges (which you can unpair)
* Discovered bridges (locally or via the remote API, which you can pair)

This is then at least a partial workaround for not being able to use local discovery and still not having your bridge connected to the internet all the time.

**Comment by paulvt** [comment]
Btw, great app! I might have time to help out in the future.

**Comment by paulvt** [comment]
Ah, I get where you coming from. It just surprised me.
Some other solutions, for example also Kodi, work by controlling them via local networks and their control apps just allow adding a bunch of name/IP address-entries, gained via auto detection/zeroconf.  The app can check if the control endpoint is online and can grey offline ones out or use a green/red light in front of them to indicate the status.

Now I think of this, if you have a list and know if one is actually online, tint can skip the BridgePage page and directly go to the rooms.

**Comment by paulvt** [comment]
Yes! Thanks a lot! :)
