### ISSUE TITLE
Add support for LIFX

### ISSUE THREAD

**Issue by JSEHV** [attah/harbour-tint#6]
Are you able to add the support for LIFX bulbs in the app or generate, based on what you already coded a LIFX app for Sailfish OS? There is a nice JS library for it:

https://github.com/mdottavio/ya-lifx

**Comment by attah** [comment]
Hmmm, probably no...
That library also uses some new hipsteresque javascript (with promises) that is too new for the current Qt/QML version on SFOS, if it's even supported at all in newer versions. (Thus why i use the 0.3 version of jshue, and not the current one). Writing another lib in the style of of old jshue, or some other way should be quite doable, however i don't think i have the time to spare for that.
Contributions welcome as always.

**Comment by JSEHV** [comment]
Ok, wasn't aware of that detailed difference. Code onwards for HUE :)
