### ISSUE TITLE
Cover page

### ISSUE THREAD

**Issue by JSEHV** [attah/harbour-tint#8]
The cover page is currently not using a grayscaled background image. This sets it off against the other Sailfish OS apps, which have a nice grayscaled, lower opacity, image. Currently your app stands out too much (see the example below).

To help you fix this, hereby I supply you the image for the cover in grayscale, in different sizes, of which one is probably sufficient.

[harbour-tint-cover.zip](https://github.com/attah/harbour-tint/files/2691193/harbour-tint-cover.zip)

I expect you can easily use and fix this, as examples can be found, eg:

https://github.com/accumulator/Quickddit/blob/master/sailfish/qml/cover/CoverPage.qml

Maybe you are even able to show a bit of info about the lights, like:

- amount of lights on
- amount of lights off

The style according to Jolla's email app would be nice in my view.

Thanks in advance!

![image 2018-12-18 16 10 53](https://user-images.githubusercontent.com/5128988/50164812-f3a4b400-02e3-11e9-9f6a-baf6db7c4f0d.jpg)

**Comment by attah** [comment]
Wow, what clean apps you have! By my standards the current cover is clearly above average, however i see now that it needs fixing. I wonder if it would look even better with the hexagons of the bulb exploded slightly apart from each other. Here are versions in 30% and 40% opacity, at a slightly smaller size as to leave space for the button(s), and 20% at a huge size (which needs higher resolution it seems).
![skarmbild_20181218_004](https://user-images.githubusercontent.com/3988878/50177137-89027100-0301-11e9-95c5-465351a2a837.png)

**Comment by JSEHV** [comment]
The biggest one has my preference... You may even make it bigger, so it goes slightly over the edges. Use the email app as an example. Just try it out. Here are a x512 and x1024 version. Should be big enough :) 

Btw. the dynamic adjustment of the size as shown on the Quickddit page is a nice one, as people have different screen resolution. Guess you include of have already included that kind of behavior too.

Bigger sizes:

[harbour-tint-cover-512-and-1024.zip](https://github.com/attah/harbour-tint/files/2692119/harbour-tint-cover-512-and-1024.zip)

**Comment by attah** [comment]
Thanks, i'll see what catches my eye... tomorrow.

**Comment by attah** [comment]
![skarmbild_20181219_001](https://user-images.githubusercontent.com/3988878/50242362-5a040200-03ca-11e9-8176-6fb1c8b8c84e.png)
Opinions?

**Comment by JSEHV** [comment]
Thinking about the light/button you want to put on the cover, maybe keep the bottom 1/3 free. Roughly the size of the email app. This way it may work well together. All these cover action buttons are also lined up that way.

_(Offtopic: Have you seen the amount of likes you get in Jolla's App Store? You've hit a highly demanded app, I know for sure!)_

**Comment by attah** [comment]
Hmm, i wouldn't quite know how to fit that and still have the bulb go outside the cover like you suggested.
(Previous picture was my suggestion on how to keep said space free). I could scrap the bulb threads on the first/last option on the latest picture. 

_OT: No,will check.. last i saw there war 9 likes out of 13 installs, which i thought was really nice._

**Comment by attah** [comment]
![skarmbild_20181219_002](https://user-images.githubusercontent.com/3988878/50244296-e533c680-03cf-11e9-9943-9cc284231b61.png)
Current status...

**Comment by JSEHV** [comment]
What if we use an angled version of the bulb, kick it a bit off the borders. 
Then the bottom is free for the cover action bulbs/buttons :)

![harbour-tint-cover-angle-x172](https://user-images.githubusercontent.com/5128988/50246014-61c8a400-03d4-11e9-9854-0f3aeb2379df.png)

All sizes:

[harbour-tint-cover-angle.zip](https://github.com/attah/harbour-tint/files/2696389/harbour-tint-cover-angle.zip)

**Comment by attah** [comment]
![skarmbild_20181219_004](https://user-images.githubusercontent.com/3988878/50246428-9be67580-03d5-11e9-99f9-a0959b18878f.png)
I think we may have a winner...

**Comment by JSEHV** [comment]
I was making a mockup too... You pick, I'm fine with your winner, I think.
I guess it is the bottom right one... Looks really cool to me at least :)

![example](https://user-images.githubusercontent.com/5128988/50246823-a0f7f480-03d6-11e9-96e3-f509cb5c7b5d.jpg)

**Comment by attah** [comment]
Yeah, i'll go for this one now. Thanks.
