### ISSUE TITLE
All lights off button on cover page

### ISSUE THREAD

**Issue by JSEHV** [attah/harbour-tint#9]
Is it possible for you to create an "all lights on/off button" on the cover page of the app?

This way you can turn on or off all lights without opening the app. Very handy when you leave or enter the house.

You can use one of the icons in the Sailfish Reference under the section "cover action" as your switch:

https://sailfishos.org/develop/docs/jolla-ambient/

If you prefer to use a different/own style icon, I've made you this one (with transparent background; the blue background is just to show here on Github how it would look like in the app on the cover)

![harbour-tint-cover-button](https://user-images.githubusercontent.com/5128988/50166807-1042eb00-02e8-11e9-851e-ef5aab80915d.png)

All sizes:

[harbour-tint-cover-button.zip](https://github.com/attah/harbour-tint/files/2691321/harbour-tint-cover-button.zip)

**Comment by attah** [comment]
Very good suggestion. I was planning the ability to have two favourites, but the global switch and in the future one favourite seems better. As you seem to have figured out, there isn't really any good icon to choose from. A power switch like that would be much better suited, but i'm not sold on the fat base of the "1" it. It doesn't look as clean as the sfos graphics in general, to me it looks almost like a speedometer. I'm curious if i can add the regular glowing dot switch somehow...

**Comment by JSEHV** [comment]
Are you sure you can't use a switch on the cover page?

https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-switch.html/

**Comment by attah** [comment]
Yes, pretty sure it needs to be a CoverAction https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-coveraction.html/
But perhaps i can go digging for the switch images...

**Comment by JSEHV** [comment]
What about these, instead of just a light (like the Sailfish standard radio button). For the lights on you can pick between the 'no glow' and 'glow' version. Shown here with background due to Githubs white background.

![bulb-switch-unavailable-bg](https://user-images.githubusercontent.com/5128988/50179384-3330c780-0307-11e9-8634-3c9fc2f0aa1d.png) (Lights unavailable, no hub found)
![bulb-switch-off-bg](https://user-images.githubusercontent.com/5128988/50179388-34fa8b00-0307-11e9-9d41-711605f3dc21.png) (Lights off)
![bulb-switch-on-bg](https://user-images.githubusercontent.com/5128988/50179393-36c44e80-0307-11e9-8b5c-3a9d8387f117.png) (Lights on, no glow)
![bulb-switch-on-bg-glow](https://user-images.githubusercontent.com/5128988/50179396-3926a880-0307-11e9-9686-7e0f16020674.png) (Lights on, glow)

All 4 versions in all sizes:

[bulb-switches.zip](https://github.com/attah/harbour-tint/files/2692094/bulb-switches.zip)

**Comment by attah** [comment]
I think these could work nicely. Since you included multiple sizes, do you have an idea on how the size should be adapting to displays with different DPI? At first glance it seems i dn't need to do anything.

**Comment by JSEHV** [comment]
I don't think you have to do that much indeed, but I don't know the nitty gritty details. Most apps seem to use 32px icons here. Standard cover icons from Jolla also seem to be 32px... Just try it out and see :) Won't hurt to learn it that way, right. Worst that can happen is that you have to fix it in a next release.
